/**
 * Bundle Mikhmon JS modules (same order as include/mikhmon-scripts.php).
 * Output: js/mikhmon.bundle.prod.js (gitignored, built on deploy).
 */
import { join } from "path";

const root = join(import.meta.dir, "..");

const modules = [
  "mikhmon/legacy-forms.js",
  "mikhmon/notify.js",
  "mikhmon/ui-toast.js",
  "mikhmon/ui-skeleton.js",
  "mikhmon/ui-session.js",
  "mikhmon/table-sort.js",
  "mikhmon/spa-intervals.js",
  "mikhmon/widget-applog.js",
  "mikhmon/widget-traffic.js",
  "mikhmon/widget-voucher-editor.js",
  "mikhmon/spa-router.js",
  "mikhmon/widget-accordion.js",
  "mikhmon/widget-lang.js",
  "mikhmon/widget-form-select.js",
  "mikhmon/bootstrap.js",
];

let source = "/* MIKFAST bundle — generated by bun run build */\n";

for (const mod of modules) {
  const path = join(root, "js", mod);
  const file = Bun.file(path);
  if (!(await file.exists())) {
    console.error(`Missing: js/${mod}`);
    process.exit(1);
  }
  source += `\n/* --- ${mod} --- */\n`;
  source += await file.text();
  source += "\n";
}

const outPath = join(root, "js", "mikhmon.bundle.prod.js");
await Bun.write(outPath, source);

console.log(`Built ${outPath} (${(source.length / 1024).toFixed(1)} KB)`);
